services:
  instagram-video-bot:
    build: .
    container_name: instagram-video-bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      # Mount temp directory for video downloads
      - ./temp:/app/temp
      # Mount cookies directory to persist authentication
      - ./cookies:/app/cookies
      # Mount logs directory (optional)
      - ./logs:/app/logs
    environment:
      # Override paths to use container paths
      - TEMP_DIR=/app/temp
      - COOKIES_FILE=/app/cookies/instagram_cookies.txt
      # Additional environment variables for container
      - TZ=UTC
    # Health check
    healthcheck:
      test: ["CMD", "python", "-m", "src.instagram_video_bot.utils.health_check"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 